version: "3.9"  # optional since v1.27.0
services:
  webserver:
    image: nginx
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
    volumes:
      - logvolume01:/var/log
  database:
    image: mariadb
    networks:
      - backend
    environment:
      MARIADB_ROOT_PASSWORD: example
networks:
  frontend: {}
  backend: {}
volumes:
  logvolume01: {}
